name: Build Image On Release

on:
  release:
    types: [published]

jobs:
  call-workflow:
    uses: linuxserver-labs/docker-actions/.github/workflows/build-image.yml@v4
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "wireguard-pia"
    secrets:
      scarf_token: ${{ secrets.SCARF_TOKEN }}
